---
title: "Performance Analysis ShExML across versions with EHRI institutions files"
author: "Herminio García-González"
date: "2024-01-31"
output: 
  html_document: default
  md_document:
    variant: markdown_github
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(summarytools)
library(FSA)
library(ggplot2)
library(rstatix)
library(rmarkdown)
```
# Set up

```{r}
datasetFull <- read.csv("C:/Users/Herminio/Git/shexml-performance-evaluation/statistics/results/resultEvaluationInstitutions.csv", sep=';')[, 2:3]
dataset <- datasetFull[(datasetFull$Engine == "ShExML-v0.3.3.jar" | datasetFull$Engine == "ShExML-v0.4.0.jar" | datasetFull$Engine == "ShExML-v0.4.2.jar" | datasetFull$Engine == "ShExML-v0.5.1.jar"), ]

```

# Descriptive statistics
```{r}
stby(dataset, dataset$Engine, descr, round.digits=5, stats=c("mean", "med", "sd", "min", "max"))
```

# Testing normality
```{r}
by(dataset$Elapsed_time.ms., dataset$Engine, shapiro.test)
```
# Running Kruskal-Wallis
```{r}
kruskal.test(Elapsed_time.ms. ~ Engine , data = dataset)
```
# Post hoc test for Kruskal-Wallis
```{r}
dunnTest(Elapsed_time.ms. ~ Engine , data = dataset, method = "bh")
```

# Effect size
```{r}
post_hoc_results <- dunn_test(Elapsed_time.ms. ~ Engine , data = dataset, p.adjust.method = "BH")
post_hoc_results$r <- post_hoc_results$statistic / sqrt(post_hoc_results$n1+post_hoc_results$n2)
post_hoc_results[, c(1,2,3,10)]
```

# Plot
```{r}
dataset[dataset$Engine=="ShExML-v0.3.2.jar", "Engine"] <- "ShExML-v0.3.2"
dataset[dataset$Engine=="ShExML-v0.3.3.jar", "Engine"] <- "ShExML-v0.3.3"
dataset[dataset$Engine=="ShExML-v0.4.0.jar", "Engine"] <- "ShExML-v0.4.0"
dataset[dataset$Engine=="ShExML-v0.4.2.jar", "Engine"] <- "ShExML-v0.4.2"
dataset[dataset$Engine=="ShExML-v0.5.1.jar", "Engine"] <- "ShExML-v0.5.1"

dataset %>%
    ggplot(aes(fill=Engine, x=Elapsed_time.ms., y=Engine)) +
        geom_violin(trim=FALSE, scale="width") +
        theme_minimal() + 
        xlab("Elapsed Time (ms)") + 
        coord_trans(x="log10")
```

```{r}
dataset[(dataset$Engine == "ShExML-v0.4.0" | dataset$Engine == "ShExML-v0.4.2" | dataset$Engine == "ShExML-v0.5.1"), ] %>%
  ggplot(aes(fill=Engine, color=Engine, x=Elapsed_time.ms.)) +
  geom_density(alpha = 0.15) +
  xlab("Elapsed time (ms)") +
  theme_minimal() + 
  theme(legend.position="bottom", text = element_text(size=15)) +
  ggtitle("Distribution of the three most performant versions", "EHRI institutions (JSON) - By Engine")
```